name: Check markdown and YAML syntax

on: [push, pull_request]

jobs:
  syntax_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate YAML syntax
      id: yaml_validation
      uses: hadolint/yaml@main
      with:
        file: .github/workflows/check_markdown_and_yaml.yml

    - name: Print YAML validation result
      run: |
        if ! echo $YAML_VALIDATION_OUTPUT | grep -Fq "Total results"; then
          echo "YAML file is not valid"
          exit 1
        else
          echo "YAML file is valid"
        fi

    - name: Validate markdown syntax
      id: md_validation
      uses: DavidAnson/markdownlint-cli@master
      with:
        files: |
          README.md
          documentation/*.md
        quiet: true
        args: --severity-threshold off

    - name: Print syntax validation result
      run: |
        grep -vchE '^#' .github/workflows/check_markdown_and_yaml.yml | grep -nwE 'error|warning'
        if [[ "$md_validation" =~ "warnings\s+found" ]]; then
          echo "Markdown files contain warnings"
        elif [[ "$md_validation" =~ "failures\s+found" ]]; then
          echo "Markdown files failed due to errors"
          exit 1
        else
          echo "Markdown files are valid"
        fi
